    DROP TABLE INTERESTED;
    DROP TABLE NOTICE;
    DROP TABLE REPLY;
    DROP TABLE TRADE;
    DROP TABLE PRODUCT_RESELL;
    DROP TABLE RESELL_INFO;
    DROP TABLE ATTACHMENT;
    DROP TABLE "LIKES";
    DROP TABLE PRODUCT;
    DROP TABLE "STYLE" CASCADE CONSTRAINTS;
    DROP TABLE USEDBOARD;
    DROP TABLE BRAND;
    DROP TABLE "CATEGORY";
    DROP TABLE "MEMBER" CASCADE CONSTRAINTS;
    DROP TABLE "COLLECTION";
    DROP TABLE MEMBER_AUTH;

    DROP SEQUENCE SEQ_NNO;          -- 공지사항
    DROP SEQUENCE SEQ_RSNO;          -- 리셀정보
    DROP SEQUENCE SEQ_TNO;          -- 트레이드
    DROP SEQUENCE SEQ_PNO;          -- 프로덕트
    DROP SEQUENCE SEQ_BNO;          -- 보드(중고)       -- 프로덕트 타입
    DROP SEQUENCE SEQ_SNO;          -- 스타일
    DROP SEQUENCE SEQ_RNO;         -- 리플라이        -- 브랜드
    DROP SEQUENCE SEQ_FNO;          --- 파일넘버
    
    CREATE SEQUENCE SEQ_NNO
    NOCACHE;
    CREATE SEQUENCE SEQ_RSNO
    NOCACHE;
    CREATE SEQUENCE SEQ_TNO
    NOCACHE;
    CREATE SEQUENCE SEQ_PNO
    NOCACHE;
    CREATE SEQUENCE SEQ_BNO
    NOCACHE;
    CREATE SEQUENCE SEQ_SNO
    NOCACHE;
    CREATE SEQUENCE SEQ_RNO
    NOCACHE;
    CREATE SEQUENCE SEQ_FNO
    NOCACHE;
    
    
    CREATE TABLE USEDBOARD (
        BOARD_NO NUMBER	NOT NULL,
        BOARD_TITLE	VARCHAR2(40) NOT NULL,
        BOARD_CONTENT VARCHAR2(300)	NOT NULL,
        STATUS VARCHAR2(40) DEFAULT 'Y' CHECK (STATUS IN('Y', 'N')) NOT NULL,
        BOARD_COUNT	NUMBER	DEFAULT 0 NOT NULL,
        CREATE_DATE	DATE DEFAULT SYSDATE NOT NULL,
        PRODUCT_TYPE_NAME	VARCHAR2(1000)	NOT NULL,
        BRAND_NAME	VARCHAR2(1000)	NOT NULL,
        BOARD_WRITER VARCHAR2(40) NOT NULL,
        BOARD_PRODUCT_NO NUMBER	NOT NULL,
        MODIFY_DATE	DATE DEFAULT SYSDATE NOT NULL,
        COLLECTION_NAME VARCHAR2(1000) NOT NULL,
        USED_PRICE NUMBER NOT NULL
    );
    
    COMMENT ON COLUMN "USEDBOARD"."BOARD_NO" IS '게시글 번호';
    
    COMMENT ON COLUMN "USEDBOARD"."BOARD_TITLE" IS '중고 게시판 제목';
    
    COMMENT ON COLUMN "USEDBOARD"."BOARD_CONTENT" IS '중고 게시판 글';
    
    COMMENT ON COLUMN "USEDBOARD"."STATUS" IS '삭제 여부 (Y/N)';
    
    COMMENT ON COLUMN "USEDBOARD"."BOARD_COUNT" IS '중고 게시판 조회수';
    
    COMMENT ON COLUMN "USEDBOARD"."CREATE_DATE" IS '중고  게시판 작성일';
    
    COMMENT ON COLUMN "USEDBOARD"."PRODUCT_TYPE_NAME" IS '카테고리(의류/신발/기타)';
    
    COMMENT ON COLUMN "USEDBOARD"."BRAND_NAME" IS '브랜드 대분류';
    
    COMMENT ON COLUMN "USEDBOARD"."BOARD_WRITER" IS '작성자';
    
    COMMENT ON COLUMN "USEDBOARD"."BOARD_PRODUCT_NO" IS 'PRODUCT  번호가 들어가거나 기타 가 들어감';
    
    COMMENT ON COLUMN "USEDBOARD"."MODIFY_DATE" IS '중고 게시글 수정 날짜';
    
    COMMENT ON COLUMN "USEDBOARD"."COLLECTION_NAME" IS '컬렉션';
    
    
    CREATE TABLE "PRODUCT" (
        "PRODUCT_NO"	NUMBER		NOT NULL,
        "PRODUCT_NAME"	VARCHAR2(100)		NOT NULL,
        "PRODUCT_CONTENT"	VARCHAR2(4000)		NOT NULL,
        "LIKES"	NUMBER	DEFAULT 0	NOT NULL,
        "COUNT"	NUMBER	DEFAULT 0	NOT NULL,
        "STATUS"	VARCHAR2(1)	DEFAULT 'Y'	CHECK (STATUS IN('Y', 'N')) NOT NULL,
        "CREATE_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
        "MODIFY_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
        "PRODUCT_WRITER"    VARCHAR2(30) DEFAULT 'admin' NOT NULL,
        "TRADE_COUNT"	NUMBER	DEFAULT 0 NULL,
        "PRODUCT_TYPE_NAME"	VARCHAR2(1000)		NOT NULL,
        "BRAND_NAME"	VARCHAR2(1000)		NOT NULL,
        "RELEASE_DATE"	DATE		NOT NULL,
        "MODEL_NO"	VARCHAR2(50)		NOT NULL,
        "COLLECTION_NAME" VARCHAR2(1000) NOT NULL,
        "RELEASE_PRICE"	VARCHAR2(50)		NOT NULL
    );
    
    COMMENT ON COLUMN "PRODUCT"."PRODUCT_NO" IS '상품번호';
    
    COMMENT ON COLUMN "PRODUCT"."PRODUCT_NAME" IS '상품이름/ 컬렉션';
    
    COMMENT ON COLUMN "PRODUCT"."PRODUCT_CONTENT" IS '상품내용';
    
    COMMENT ON COLUMN "PRODUCT"."LIKES" IS '상품 좋아요 수';
    
    COMMENT ON COLUMN "PRODUCT"."COUNT" IS '상품 조회수';
    
    COMMENT ON COLUMN "PRODUCT"."STATUS" IS '상태';
    
    COMMENT ON COLUMN "PRODUCT"."CREATE_DATE" IS '작성일자';
    
    COMMENT ON COLUMN "PRODUCT"."MODIFY_DATE" IS '수정일자';
    
    COMMENT ON COLUMN "PRODUCT"."PRODUCT_WRITER" IS '작성자';
    
    COMMENT ON COLUMN "PRODUCT"."BRAND_NAME" IS '브랜드 대분류';
    
    COMMENT ON COLUMN "PRODUCT"."PRODUCT_TYPE_NAME" IS '카테고리(의류/신발/기타)';
    
    COMMENT ON COLUMN "PRODUCT"."COLLECTION_NAME" IS '컬렉션';
    
    COMMENT ON COLUMN "PRODUCT"."TRADE_COUNT" IS '거래량';
    
    COMMENT ON COLUMN "PRODUCT"."RELEASE_DATE" IS '발매일자';
    
    COMMENT ON COLUMN "PRODUCT"."MODEL_NO" IS '모델번호';
    
    COMMENT ON COLUMN "PRODUCT"."RELEASE_PRICE" IS '발매가';
    
    
    CREATE TABLE "INTERESTED" (
        "USER_ID"    VARCHAR2(40)        NOT NULL,
        "PRODUCT_NO"    NUMBER,
        "USED_NO"    NUMBER
    );
    
    COMMENT ON COLUMN "INTERESTED"."USER_ID" IS '회원 아이디';
    
    COMMENT ON COLUMN "INTERESTED"."PRODUCT_NO" IS '좋아하는 상품번호';
    
    COMMENT ON COLUMN "INTERESTED"."USED_NO" IS '게시글 번호';
    
    
    CREATE TABLE "STYLE" (
        "STYLE_NO"	NUMBER		NOT NULL,
        "STYLE_TAG"   VARCHAR2(1000),
        "STYLE_CONTENT"	VARCHAR2(1000)	NOT	NULL,
        "STATUS"	VARCHAR2(1)	DEFAULT 'Y'	CHECK (STATUS IN('Y', 'N')) NOT NULL,
        "COUNT"	NUMBER	DEFAULT 0	NOT NULL,
        "LIKE"	NUMBER	DEFAULT 0	NOT NULL,
        "CREATE_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
        "MODIFY_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
        "STYLE_WRITER"	VARCHAR2(200)		NOT NULL
    );
    
    COMMENT ON COLUMN "STYLE"."STYLE_NO" IS '스타일 글번호';
    
    COMMENT ON COLUMN "STYLE"."STYLE_TAG" IS '해시 태그';
    
    COMMENT ON COLUMN "STYLE"."STYLE_CONTENT" IS '스타일 내용';
    
    COMMENT ON COLUMN "STYLE"."STATUS" IS '상태';
    
    COMMENT ON COLUMN "STYLE"."COUNT" IS '조회수';
    
    COMMENT ON COLUMN "STYLE"."LIKE" IS '좋아요 수';
    
    COMMENT ON COLUMN "STYLE"."CREATE_DATE" IS '작성일자';
    
    COMMENT ON COLUMN "STYLE"."MODIFY_DATE" IS '수정일자';
    
    COMMENT ON COLUMN "STYLE"."STYLE_WRITER" IS '작성자';
    
    
    CREATE TABLE "NOTICE" (
        "NOTICE_NO"	NUMBER		NOT NULL,
        "NOTICE_TITLE"	VARCHAR2(50)		NOT NULL,
        "NOTICE_CONTENT"	VARCHAR2(4000)		NOT NULL,
        "NOTICE_COUNT"    NUMBER    DEFAULT 0 NOT NULL,
        "CREATE_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
        "MODIFY_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
        "STATUS"	VARCHAR2(2)	DEFAULT 'Y'	CHECK (STATUS IN('Y', 'N')) NOT NULL,
        "NOTICE_WRITER"    VARCHAR2(40) DEFAULT 'admin' NOT NULL,
        "NOTICE_TYPE" VARCHAR2(2) DEFAULT 'N' CHECK (NOTICE_TYPE IN('N', 'Q')) NOT NULL
    );
    
    COMMENT ON COLUMN "NOTICE"."NOTICE_NO" IS '공지사항';
    
    COMMENT ON COLUMN "NOTICE"."NOTICE_COUNT" IS '공지사항 조회수';
    
    COMMENT ON COLUMN "NOTICE"."CREATE_DATE" IS '생성일자';
    
    COMMENT ON COLUMN "NOTICE"."MODIFY_DATE" IS '수정일자';
    
    COMMENT ON COLUMN "NOTICE"."STATUS" IS '삭제여부';
    
    COMMENT ON COLUMN "NOTICE"."NOTICE_WRITER" IS '회원 아이디';
    
    COMMENT ON COLUMN "NOTICE"."NOTICE_TYPE" IS '글 종류(N:공지사항, Q: 질문)';
    
    
    CREATE TABLE "REPLY" (
        "REPLY_NO"	NUMBER		NOT NULL,
        "REPLY_WRITER"	VARCHAR2(50)		NOT NULL,
        "REPLY_CONTENT"	VARCHAR2(200)		NOT NULL,
        "REPLY_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
        "STATUS"	VARCHAR2(1)	DEFAULT 'Y' CHECK (STATUS IN('Y', 'N'))	NOT NULL,
        "STYLE_NO"	NUMBER		NOT NULL
    );
    
    COMMENT ON COLUMN "REPLY"."REPLY_NO" IS '댓글번호';
    
    COMMENT ON COLUMN "REPLY"."REPLY_WRITER" IS '작성자아이디';
    
    COMMENT ON COLUMN "REPLY"."REPLY_CONTENT" IS '댓글내용';
    
    COMMENT ON COLUMN "REPLY"."REPLY_DATE" IS '작성일';
    
    COMMENT ON COLUMN "REPLY"."STATUS" IS '상태값(Y:존재/N:삭제/R:신고)';
    
    COMMENT ON COLUMN "REPLY"."STYLE_NO" IS '스타일번호';
    
    
    CREATE TABLE "TRADE" (
        "TRADE_NO"	NUMBER		NOT NULL,
        "RECEIVER_NAME"	VARCHAR2(20)		NOT NULL,
        "RECEIVER_PHONE"	VARCHAR2(20)		NOT NULL,
        "RECEVIER_ADDRESS"	VARCHAR2(100)		NOT NULL,
        "ODER_COMMENT"	VARCHAR2(300)           NOT NULL,
        "PAYMENT"	NUMBER		NOT NULL,
        "PURCHASE_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
        "STATUS"	VARCHAR2(100)	DEFAULT 'Y'	CHECK (STATUS IN('Y', 'N')) NOT NULL,
        "DELIVERY"	VARCHAR2(100)	DEFAULT 'Y'	CHECK (DELIVERY IN('Y', 'A', 'E')) NOT NULL,
        "PRODUCT_NO"	NUMBER		NOT NULL,
        "BUYER"	VARCHAR2(200)		NOT NULL,
        "SELLER"	VARCHAR2(200)	NOT	NULL,
        "RESELL_NO"	NUMBER		NOT NULL
    );
    
    COMMENT ON COLUMN "TRADE"."TRADE_NO" IS '거래번호';
    
    COMMENT ON COLUMN "TRADE"."RECEIVER_NAME" IS '수령자이름';
    
    COMMENT ON COLUMN "TRADE"."RECEIVER_PHONE" IS '수령자폰번호';
    
    COMMENT ON COLUMN "TRADE"."RECEVIER_ADDRESS" IS '배송지';
    
    COMMENT ON COLUMN "TRADE"."ODER_COMMENT" IS '배송요청사항';
    
    COMMENT ON COLUMN "TRADE"."PAYMENT" IS '결제금액';
    
    COMMENT ON COLUMN "TRADE"."PURCHASE_DATE" IS '결제일';
    
    COMMENT ON COLUMN "TRADE"."STATUS" IS '결재상태(Y:결재완료/ N:결재실패)';
    
    COMMENT ON COLUMN "TRADE"."DELIVERY" IS '배송상태(Y:배송대기/A:배송중/E:배송완료)';
    
    COMMENT ON COLUMN "TRADE"."PRODUCT_NO" IS '상품번호';
    
    COMMENT ON COLUMN "TRADE"."BUYER" IS '구매자 회원 아이디';
    
    COMMENT ON COLUMN "TRADE"."SELLER" IS '판매자 회원 아이디';
    
    COMMENT ON COLUMN "TRADE"."RESELL_NO" IS '리셀번호';
    
    
       
    CREATE TABLE "MEMBER" (
        "USER_ID"    VARCHAR2(200)        NOT NULL,
        "USER_PWD"    VARCHAR2(200)        NOT NULL,
        "USER_NAME"    VARCHAR2(20)        NOT NULL,
        "EMAIL"    VARCHAR2(50)        NOT NULL,
        "ADDRESS"    VARCHAR2(1000)        NOT NULL,
        "BIRTH_DATE"    DATE    DEFAULT SYSDATE    NOT NULL,
        "GENDER"    VARCHAR2(1)    DEFAULT 'F'    CHECK (GENDER IN ('F', 'M')) NOT NULL,
        "STATUS"    VARCHAR2(1)    DEFAULT 'Y'    CHECK (STATUS IN('Y', 'N')) NOT NULL,
        "ENROLL_DATE"    DATE    DEFAULT SYSDATE    NOT NULL,
        "MODIFY_DATE"    DATE    DEFAULT SYSDATE    NOT NULL,
        "PHONE"    VARCHAR2(20)        NOT NULL,
        "NICKNAME"    VARCHAR2(200)        NOT NULL,
        "MEMBER_AUTH" NUMBER DEFAULT 0
    );
    
    
    COMMENT ON COLUMN "MEMBER"."USER_ID" IS '회원 아이디';
    
    COMMENT ON COLUMN "MEMBER"."USER_PWD" IS '회원 비밀번호';
    
    COMMENT ON COLUMN "MEMBER"."USER_NAME" IS '회원 이름';
    
    COMMENT ON COLUMN "MEMBER"."EMAIL" IS '이메일';
    
    COMMENT ON COLUMN "MEMBER"."ADDRESS" IS '주소';
    
    COMMENT ON COLUMN "MEMBER"."BIRTH_DATE" IS '생일';
    
    COMMENT ON COLUMN "MEMBER"."GENDER" IS '성별';
    
    COMMENT ON COLUMN "MEMBER"."STATUS" IS '회원 상태';
    
    COMMENT ON COLUMN "MEMBER"."ENROLL_DATE" IS '회원가입일자';
    
    COMMENT ON COLUMN "MEMBER"."MODIFY_DATE" IS '회원정보수정일자';
    
    COMMENT ON COLUMN "MEMBER"."PHONE" IS '핸드폰번호';
    
    COMMENT ON COLUMN "MEMBER"."NICKNAME" IS '별명';
    
    
    CREATE TABLE "PRODUCT_RESELL" (
        "PRODUCT_NO"	NUMBER		NOT NULL,
        "PRODUCT_AMOUNT"	NUMBER	 NULL,
        "PRODUCT_SIZE"	VARCHAR2(30)		NOT NULL
    );
    
    COMMENT ON COLUMN "PRODUCT_RESELL"."PRODUCT_NO" IS '상품번호';
    
    COMMENT ON COLUMN "PRODUCT_RESELL"."PRODUCT_AMOUNT" IS '재고량';
    
    
    
    CREATE TABLE "BRAND" (
        "BRAND_NAME"	VARCHAR2(1000)		NOT NULL
    );
    
    COMMENT ON COLUMN "BRAND"."BRAND_NAME" IS '브랜드 대분류';
    
    
    
    CREATE TABLE "RESELL_INFO" (
        "RESELL_NO"	NUMBER		NOT NULL,
        "PRODUCT_NO"	NUMBER		NOT NULL,
        "SELLER"	VARCHAR2(200)		NOT NULL,
        "PRODUCT_SIZE"	VARCHAR2(50)		NOT NULL,
        "PRODUCT_AMOUNT"	NUMBER	NOT NULL,
        "RESELL_UPLOAD_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
        "RESELL_DATE"	DATE	DEFAULT  NULL,
        "RESELL_PRICE"	NUMBER		NOT NULL,
        STATUS VARCHAR2(1) DEFAULT 'Y' CHECK(STATUS IN('Y', 'O', 'N'))
    );
    
    COMMENT ON COLUMN "RESELL_INFO"."RESELL_NO" IS '리셀번호';
    
    COMMENT ON COLUMN "RESELL_INFO"."PRODUCT_NO" IS '상품번호';
    
    COMMENT ON COLUMN "RESELL_INFO"."SELLER" IS '판매자 아이디';
    
    COMMENT ON COLUMN "RESELL_INFO"."PRODUCT_SIZE" IS '판매 사이즈';
    
    COMMENT ON COLUMN "RESELL_INFO"."PRODUCT_AMOUNT" IS '판매 갯수';
    
    COMMENT ON COLUMN "RESELL_INFO"."RESELL_UPLOAD_DATE" IS '판매 등록 날짜';
    
    COMMENT ON COLUMN "RESELL_INFO"."RESELL_DATE" IS '판매 날짜';
    
    COMMENT ON COLUMN "RESELL_INFO"."RESELL_PRICE" IS '판매 가격';
    
    
    
    CREATE TABLE "CATEGORY" (
        "PRODUCT_TYPE_NAME"	VARCHAR2(1000)		NOT NULL
    );
    
    COMMENT ON COLUMN "CATEGORY"."PRODUCT_TYPE_NAME" IS '카테고리(의류/신발/기타)';
    
    CREATE TABLE "COLLECTION" (
        "COLLECTION_NAME" VARCHAR2(1000) PRIMARY KEY
    );
    
    COMMENT ON COLUMN "COLLECTION"."COLLECTION_NAME" IS '컬렉션';
    
    
    
    CREATE TABLE "ATTACHMENT" (
        "FILE_NO"	NUMBER		NOT NULL,
        "ORIGIN_NAME"	VARCHAR2(1000)		NOT NULL,
        "CHANGE_NAME"	VARCHAR2(1000)		NOT NULL,
        "FILE_PATH"	VARCHAR2(1000)		NOT NULL,
        "UPLOAD_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
        "FILE_LEVEL"	NUMBER		NOT NULL,
        "STATUS"	VARCHAR2(1)	DEFAULT 'Y'	CHECK (STATUS IN('Y', 'N')) NOT NULL,
        "REF_NO"    NUMBER NOT NULL,
        "TYPE_NO"      NUMBER CHECK (TYPE_NO IN(1,2,3,4)) NOT NULL 
    );
    
    COMMENT ON COLUMN "ATTACHMENT"."FILE_NO" IS '파일번호';
    
    COMMENT ON COLUMN "ATTACHMENT"."ORIGIN_NAME" IS '파일원본명';
    
    COMMENT ON COLUMN "ATTACHMENT"."CHANGE_NAME" IS '파일수정명';
    
    COMMENT ON COLUMN "ATTACHMENT"."FILE_PATH" IS '저장폴더경로';
    
    COMMENT ON COLUMN "ATTACHMENT"."UPLOAD_DATE" IS '업로드일';
    
    COMMENT ON COLUMN "ATTACHMENT"."FILE_LEVEL" IS '1일때 섬네일/2일때 일반사진';
    
    COMMENT ON COLUMN "ATTACHMENT"."STATUS" IS '상태';
    
    COMMENT ON COLUMN "ATTACHMENT"."REF_NO" IS 'REF_BNO';
    
    COMMENT ON COLUMN "ATTACHMENT"."TYPE_NO" IS '분류번호(1 리셀 ,2 중고 ,3 스타일 4, 기타)';
    
    
    
    
    
    CREATE TABLE "LIKES" (
        "USER_ID"	VARCHAR2(40)		NOT NULL,
        "STYLE_NO"	NUMBER		NOT NULL
    );
    
    COMMENT ON COLUMN "LIKES"."USER_ID" IS '회원 아이디';
    
    COMMENT ON COLUMN "LIKES"."STYLE_NO" IS '스타일 번호';
    
    
    CREATE TABLE MEMBER_AUTH(
    
    EMAIL VARCHAR2(100),
    AUTHKEY VARCHAR2(50)
    
    );

   
    ALTER TABLE "USEDBOARD" ADD CONSTRAINT "PK_USEDBOARD" PRIMARY KEY (
        "BOARD_NO"
    );
    
    ALTER TABLE "PRODUCT" ADD CONSTRAINT "PK_PRODUCT" PRIMARY KEY (
        "PRODUCT_NO"
    );
    
    ALTER TABLE "STYLE" ADD CONSTRAINT "PK_STYLE" PRIMARY KEY (
        "STYLE_NO"
    );
    
    ALTER TABLE "NOTICE" ADD CONSTRAINT "PK_NOTICE" PRIMARY KEY (
        "NOTICE_NO"
    );
    
    ALTER TABLE "REPLY" ADD CONSTRAINT "PK_REPLY" PRIMARY KEY (
        "REPLY_NO"
    );
    
    ALTER TABLE "TRADE" ADD CONSTRAINT "PK_TRADE" PRIMARY KEY (
        "TRADE_NO"
    );
    
    ALTER TABLE "MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY (
        "USER_ID"
    );
    
    ALTER TABLE "BRAND" ADD CONSTRAINT "PK_BRAND" PRIMARY KEY (
        "BRAND_NAME"
    );
    
    ALTER TABLE "RESELL_INFO" ADD CONSTRAINT "PK_RESELL" PRIMARY KEY (
        "RESELL_NO"
    );
    
    ALTER TABLE "CATEGORY" ADD CONSTRAINT "PK_CATEGORY" PRIMARY KEY (
        "PRODUCT_TYPE_NAME"
    );
    
    ALTER TABLE "ATTACHMENT" ADD CONSTRAINT "PK_ATTACHMENT" PRIMARY KEY (
        "FILE_NO"
    );
    
    ALTER TABLE "USEDBOARD" ADD CONSTRAINT "FK_CATEGORY_TO_USEDBOARD_1" FOREIGN KEY (
        "PRODUCT_TYPE_NAME"
    )
    REFERENCES "CATEGORY" (
        "PRODUCT_TYPE_NAME"
    );
    
    ALTER TABLE "USEDBOARD" ADD CONSTRAINT "FK_BRAND_TO_USEDBOARD_1" FOREIGN KEY (
        "BRAND_NAME"
    )
    REFERENCES "BRAND" (
        "BRAND_NAME"
    );
    
    
    
    ALTER TABLE "USEDBOARD" ADD CONSTRAINT "FK_MEMBER_TO_USEDBOARD_1" FOREIGN KEY (
        "BOARD_WRITER"
    )
    REFERENCES "MEMBER" (
        "USER_ID"
    );
    
    ALTER TABLE "PRODUCT" ADD CONSTRAINT "FK_MEMBER_TO_PRODUCT_1" FOREIGN KEY (
        "PRODUCT_WRITER"
    )
    REFERENCES "MEMBER" (
        "USER_ID"
    );
    
    ALTER TABLE "PRODUCT" ADD CONSTRAINT "FK_CATEGORY_TO_PRODUCT_1" FOREIGN KEY (
        "PRODUCT_TYPE_NAME"
    )
    REFERENCES "CATEGORY" (
        "PRODUCT_TYPE_NAME"
    );
    
    ALTER TABLE "PRODUCT" ADD CONSTRAINT "FK_BRAND_TO_PRODUCT_1" FOREIGN KEY (
        "BRAND_NAME"
    )
    REFERENCES "BRAND" (
        "BRAND_NAME"
    );
    
    ALTER TABLE "INTERESTED" ADD CONSTRAINT "FK_MEMBER_TO_INTERESTED_1" FOREIGN KEY (
        "USER_ID"
    )
    REFERENCES "MEMBER" (
        "USER_ID"
    );
    
    ALTER TABLE "INTERESTED" ADD CONSTRAINT "FK_PRODUCT_TO_INTERESTED_1" FOREIGN KEY (
        "PRODUCT_NO"
    )
    REFERENCES "PRODUCT" (
        "PRODUCT_NO"
    );
    
    ALTER TABLE "INTERESTED" ADD CONSTRAINT "FK_USEDBOARD_TO_INTERESTED_1" FOREIGN KEY (
        "USED_NO"
    )
    REFERENCES "USEDBOARD" (
        "BOARD_NO"
    );
    
    ALTER TABLE "STYLE" ADD CONSTRAINT "FK_MEMBER_TO_STYLE_1" FOREIGN KEY (
        "STYLE_WRITER"
    )
    REFERENCES "MEMBER" (
        "USER_ID"
    );
    
    ALTER TABLE "NOTICE" ADD CONSTRAINT "FK_MEMBER_TO_NOTICE_1" FOREIGN KEY (
        "NOTICE_WRITER"
    )
    REFERENCES "MEMBER" (
        "USER_ID"
    );
    
    ALTER TABLE "REPLY" ADD CONSTRAINT "FK_STYLE_TO_REPLY_1" FOREIGN KEY (
        "STYLE_NO"
    )
    REFERENCES "STYLE" (
        "STYLE_NO"
    );
    
    ALTER TABLE "TRADE" ADD CONSTRAINT "FK_PRODUCT_TO_TRADE_1" FOREIGN KEY (
        "PRODUCT_NO"
    )
    REFERENCES "PRODUCT" (
        "PRODUCT_NO"
    );
    
    ALTER TABLE "TRADE" ADD CONSTRAINT "FK_MEMBER_TO_TRADE_1" FOREIGN KEY (
        "BUYER"
    )
    REFERENCES "MEMBER" (
        "USER_ID"
    );
    
    ALTER TABLE "TRADE" ADD CONSTRAINT "FK_RESELL_TO_TRADE_1" FOREIGN KEY (
        "RESELL_NO"
    )
    REFERENCES "RESELL_INFO" (
        "RESELL_NO"
    );
    
    ALTER TABLE "PRODUCT_RESELL" ADD CONSTRAINT "FK_PRODUCT_TO_PRODUCT_RESELL_1" FOREIGN KEY (
        "PRODUCT_NO"
    )
    REFERENCES "PRODUCT" (
        "PRODUCT_NO"
    );
    
    ALTER TABLE "RESELL_INFO" ADD CONSTRAINT "FK_PRODUCT_TO_RESELL_1" FOREIGN KEY (
        "PRODUCT_NO"
    )
    REFERENCES "PRODUCT" (
        "PRODUCT_NO"
    );
    
    ALTER TABLE "RESELL_INFO" ADD CONSTRAINT "FK_MEMBER_TO_RESELL_1" FOREIGN KEY (
        "SELLER"
    )
    REFERENCES "MEMBER" (
        "USER_ID"
    );
    
    ALTER TABLE "LIKES" ADD CONSTRAINT "FK_MEMBER_TO_LIKE_1" FOREIGN KEY (
        "USER_ID"
    )
    REFERENCES "MEMBER" (
        "USER_ID"
    );
    
    ALTER TABLE "LIKES" ADD CONSTRAINT "FK_STYLE_TO_LIKE_1" FOREIGN KEY (
        "STYLE_NO"
    )
    REFERENCES "STYLE" (
        "STYLE_NO"
    );
    
    ALTER TABLE "USEDBOARD" ADD CONSTRAINT "FK_COLLECTION_TO_USEDBOARD" FOREIGN KEY (
        "COLLECTION_NAME"
    )
    REFERENCES "COLLECTION" (
        "COLLECTION_NAME"
    );
    
    ALTER TABLE "PRODUCT" ADD CONSTRAINT "FK_COLLECTION_TO_PRODUCT" FOREIGN KEY (
        "COLLECTION_NAME"
    )
    REFERENCES "COLLECTION" (
        "COLLECTION_NAME"
    );
    
    
    
    -- 1234, pass01, pass02 암호화
    INSERT INTO MEMBER VALUES ('admin', '1234', '관리자', 'admin@email', '서울시', sysdate, default, default, SYSDATE, SYSDATE, '01000000000', '관리자',DEFAULT);
    INSERT INTO MEMBER VALUES ('user01', 'pass01', '일유저', 'user01@email', '경기도', sysdate, default, default, SYSDATE, SYSDATE, '01011111111', '유저일',DEFAULT);
    INSERT INTO MEMBER VALUES ('user02', 'pass02', '이유저', 'user02@email', '경기도', sysdate, default, default, SYSDATE, SYSDATE, '01022222222', '유저이',DEFAULT);
    
    INSERT INTO CATEGORY VALUES('의류');
    INSERT INTO CATEGORY VALUES('신발');
    INSERT INTO CATEGORY VALUES('기타');
    
    INSERT INTO BRAND VALUES('NIKE');
    INSERT INTO BRAND VALUES('ADIDAS');
    INSERT INTO BRAND VALUES('NEWBALANCE');
    INSERT INTO BRAND VALUES('LOISVUITON');
    INSERT INTO BRAND VALUES('PRADA');
    INSERT INTO BRAND VALUES('ROLEX');
    INSERT INTO BRAND VALUES('CARTIER');
    INSERT INTO BRAND VALUES('BOTTEGA VENETA');
    INSERT INTO BRAND VALUES('APPLE');
    INSERT INTO BRAND VALUES('DYSON');
    INSERT INTO BRAND VALUES('STONEISLAND');
    INSERT INTO BRAND VALUES('MAISON MARGIELA');
    INSERT INTO BRAND VALUES('HERMES');
    INSERT INTO BRAND VALUES('CHANEL');
    INSERT INTO BRAND VALUES('DIOR');
    INSERT INTO BRAND VALUES('MIHARA YASUHIRO');
    INSERT INTO BRAND VALUES('WOOYOUNGMI');
    INSERT INTO BRAND VALUES('BELENCIAGA');
    INSERT INTO BRAND VALUES('CONVERSE');
    INSERT INTO BRAND VALUES('STUSSY');
    INSERT INTO BRAND VALUES('JORDAN');
    
    
    
    
    
    
    INSERT INTO COLLECTION VALUES('LUXURY');
    INSERT INTO COLLECTION VALUES('JORDAN 1');
    INSERT INTO COLLECTION VALUES('JORDAN 3');
    INSERT INTO COLLECTION VALUES('JORDAN 4');
    INSERT INTO COLLECTION VALUES('JORDAN 5');
    INSERT INTO COLLECTION VALUES('JORDAN 6');
    INSERT INTO COLLECTION VALUES('JORDAN 11');
    INSERT INTO COLLECTION VALUES('JORDAN 13');
    INSERT INTO COLLECTION VALUES('NIKE DUNK');
    INSERT INTO COLLECTION VALUES('NIKE AIR FORCE');
    INSERT INTO COLLECTION VALUES('NIKE AIR MAX 1');
    INSERT INTO COLLECTION VALUES('NIKE AIR MAX 95');
    INSERT INTO COLLECTION VALUES('NIKE AIR MAX 97');
    INSERT INTO COLLECTION VALUES('NIKE AIR MAX VAPORMAX');
    INSERT INTO COLLECTION VALUES('NIKE DAYBREAK');
    INSERT INTO COLLECTION VALUES('NIKE UPTEMPO');
    INSERT INTO COLLECTION VALUES('NIKE KOBE');
    INSERT INTO COLLECTION VALUES('NIKE BLAZER');
    INSERT INTO COLLECTION VALUES('NEW BALANCE 237');
    INSERT INTO COLLECTION VALUES('NEW BALANCE 327');
    INSERT INTO COLLECTION VALUES('NEW BALANCE 530');
    INSERT INTO COLLECTION VALUES('NEW BALANCE 990');
    INSERT INTO COLLECTION VALUES('NEW BALANCE 991');
    INSERT INTO COLLECTION VALUES('NEW BALANCE 992');
    INSERT INTO COLLECTION VALUES('NEW BALANCE 993');
    INSERT INTO COLLECTION VALUES('NEW BALANCE 1300');
    INSERT INTO COLLECTION VALUES('NEW BALANCE 2002');
    INSERT INTO COLLECTION VALUES('CONVERSE RUN STAR');
    INSERT INTO COLLECTION VALUES('CONVERSE CHUCK 70');
    INSERT INTO COLLECTION VALUES('ADIDAS YEEZY');
    INSERT INTO COLLECTION VALUES('ADIDAS SUPERSTAR');
    INSERT INTO COLLECTION VALUES('X OFF-WHITE');
    INSERT INTO COLLECTION VALUES('X TRIVIS SCOTT');
    INSERT INTO COLLECTION VALUES('X SACAI');
    INSERT INTO COLLECTION VALUES('X UNDERCOVER');
    INSERT INTO COLLECTION VALUES('X SUPREME');
    INSERT INTO COLLECTION VALUES('X FEAR OF GOD');
    INSERT INTO COLLECTION VALUES('X PEACEMINUSONE');
    INSERT INTO COLLECTION VALUES('WOOYOUNGMI FLOWER');
    INSERT INTO COLLECTION VALUES('STUSSY PANTS');
    INSERT INTO COLLECTION VALUES('STUSSY DICE');
    INSERT INTO COLLECTION VALUES('NIKE X ');
    INSERT INTO COLLECTION VALUES('ROLEX SUBMARINER');
    INSERT INTO COLLECTION VALUES('HERMES BAG');
    INSERT INTO COLLECTION VALUES('HERMES JEWELRY');

    COMMIT;